### ISSUE TITLE
Meshes with high polygon counts export incorrectly

### ISSUE THREAD

**Issue by Lasercar** [DarklightGames/io_export_psk_psa#7] opened 2021-09-05 12:56 UTC
Trying to export a 53K tri object, with 30K verts, results in a broken 40K vert, 52K model, with tons of artifacts and bits of the mesh missing.

Model in question:
https://www.moddb.com/games/unreal-tournament-2004/addons/high-poly-scorpion
https://sketchfab.com/3d-models/free-scorpion-ut2004-finished-9c337d0da10f49629877a0631a39c99e

I'm able to export it using ActorX (in 3dsmax) without any issues by unticking bake smoothing groups.

**Comment by cmbasnett** [comment] 2021-09-07 07:05
Hi @Lasercar, I will have a look at this and try to identify the issue.

**Comment by cmbasnett** [comment] 2021-09-07 07:48
![image](https://user-images.githubusercontent.com/5035660/132301372-70d8a294-205a-4bb1-9036-33a07b32f7d2.png)

I have reproduced the error. I have a suspicion as to what might be the cause. Models with more than 65536 wedges use a different internal structure for how they are represented. For our team's own uses, we never have any models with such high poly-counts and so never encountered this. I will look into a fix for this.

**Comment by cmbasnett** [comment] 2021-09-08 05:05
This bug has been fixed in release [1.1.1](https://github.com/DarklightGames/io_export_psk_psa/releases/tag/1.1.1). Thank you for the report!

![image](https://user-images.githubusercontent.com/5035660/132449534-db77a9be-2614-4cb8-99ad-f4950d1dd03f.png)

**Closed by cmbasnett** 2021-09-08 05:05 UTC
Labels: bug
